name: CI - Build, Tests et Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    name: Back
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v4
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Build et Tests
        working-directory: back
        run: mvn clean test

      - name: Présence du rapport JaCoCo
        run: ls -l back/target/site/jacoco/

      - name: Upload rapport JaCoCo
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco/jacoco.xml

  frontend-tests:
    name: Front
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: front/package-lock.json

      - name: Installer les dépendances
        run: npm ci

      - name: Lancer les tests Angular avec coverage
        run: npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage

      - name: Présence du rapport Karma coverage
        run: ls -l front/coverage/ || true

      - name: Upload rapport Karma coverage
        uses: actions/upload-artifact@v4
        with:
          name: karma-coverage
          path: front/coverage/

  sonar-analysis:
    name: Analyse SonarCloud
    runs-on: ubuntu-latest
    needs: [ backend-tests, frontend-tests ]

    steps:
      - name: Checkout v4
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download backend coverage report
        uses: actions/download-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco/

      - name: Download frontend coverage report
        uses: actions/download-artifact@v4
        with:
          name: karma-coverage
          path: front/coverage/bobapp/

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Build backend
        working-directory: back
        run: mvn -B clean package -DskipTests

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: front
        run: npm ci

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=killiadmin_bobapp
            -Dsonar.organization=killiadmin
            -Dsonar.sources=back/src,front/src
            -Dsonar.tests=back/src/test,front/src
            -Dsonar.exclusions=**/node_modules/**,**/test/**,**/*.spec.ts,**/build-wrapper-dump.json
            -Dsonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
            -Dsonar.javascript.lcov.reportPaths=front/coverage/bobapp/lcov.info
            -Dsonar.java.binaries=back/target/classes
            -Dsonar.java.libraries=back/target/**/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

